---
name: Hooks directory
  ansible.builtin.file:
    dest: "/etc/networkd-dispatcher/{{ hook }}"
    state: directory

name: Add hooks
  ansible.builtin.template:
    template: templates/ethtool-hook.sh.j2
    dest: "/etc/networkd-dispatcher/{{ hook }}/99-ethtool-{{ interface_name }}-{{ item }}"
  loop: "{{ interface_features }}"
